README.md, src/light-godwoken/lightGodwokenType.ts
- add deposit interface
- docs: fix typo and remove verbose descriptions
=> zhangyouxin

src/views/Deposit.tsx
deposit时，如果ckb 余额小于64，在ckb输入框输入大于400的值，页面会白屏。这个提交修复了这个bug
=> fix: error if input ckb amount while ckb balance is less than 64ckb

src/light-godwoken/LightGodwokenV1.ts, src/light-godwoken/constants/godwokenTokensV0.ts, src/light-godwoken/constants/godwokenTokensV1.ts, src/light-godwoken/constants/lightGodwokenConfig.ts, src/light-godwoken/constants/tokens.ts
This PR enhanced:
- the `0x0000000000000000000000000000000000000000` in unnecessary when deposit or withdrawal
- multicall2 for godwoken mainnet v0
- cannot fetch token list on godwoken v0 mainnet
=> fix: cannot load token list on godwoken v0 mainnet

src/components/Withdrawal/RequestWithdrawalV1.tsx, src/components/Withdrawal/service.ts, src/light-godwoken/LightGodwokenV0.ts, src/light-godwoken/LightGodwokenV1.ts, src/light-godwoken/constants/error.ts
motivation: User will get stuck if he/she deposits asset to layer 2 and then withdraw immediatlly, we should tell user why withdrawal fails.
The reason is tokens should stay on layer 2 for some time(will make it acurate in future PR) until it can be withdrawed.
=> feat: prompt user message if withdrawal fail

src/light-godwoken/constants/lightGodwokenConfig.ts
This PR has: 
- updated mainnet-v1 multicall to multicallv3
- updated testnet-v1 multicall to multicallv3
---
refer to:
- https://github.com/mds1/multicall/commit/a6ed03f4bb232a573e9f6d4bdeca21a4edd3c1f7
Thanks to @Kuzirashi and @mds1
---
=> feat: update mainnet-v1 and testnet-v1 multicallv3 contract address

src/components/Withdrawal/ListV0.tsx, src/components/Withdrawal/ListV1.tsx, src/components/Withdrawal/RequestWithdrawalV0.tsx, src/components/Withdrawal/RequestWithdrawalV1.tsx
motivation: Users don't know where their assets are when they make a withdrawal request so they could get anxious about losing their funds.
This pr has:
- added a more detailed prompt when a user makes a withdrawal request
- added tooltip in the pending list
---
=> feat: tips for withdrawal info will appear within 5 min

docs/introduction.md
line 151: withdraw - withdrawal
line 162: build -> built
line 162: dAPP -> dApps
line 166: unkonwn -> unknown - on Godwoken Bridge page -> on the Godwoken Bridge page -  this is because that your account is not registered on Godwoken network - this may be because your account is not registered on the Godwoken network. This can be fixed by depositing some CKB to the Godwoken network, then the issue should be resolved.
=> docs: fixing syntax

src/components/Withdrawal/ListV0.tsx, src/light-godwoken/LightGodwokenV0.ts
motivation: We use Scanner API to fetch withdrawal list of user: 
```
curl --location --request GET 'https://api.gwscan.com/api/withdrawal_histories?owner_lock_hash=0xc10d05d15d8f1c4295df6d58490xc6a1a6daebe448bad1d8af8580305d9482a5c8'
```
this only returns normal withdrawal list, if we want to fetch fast withdrawal list of godwoken v0 user, we need to pass `v1 deposit lock hash` to `owner_lock_hash` in the API above.
This PR has:
- fetch v0 user's withdrawal list by making two request mentioned above.
- merge, and two lists  by `block_number` in desc order.
---
---
**Problem:**
As we can see in the image above, there are sevral fast withdrawal pending for more than expected time, this may be problem introduced by Scanner API.
Here is return value of Scanner API:  
- user eth address: …
=> feat: fetch fast withdrawal list by v1 deposit lock hash

.gitignore, src/light-godwoken/LightGodwokenV0.ts, src/light-godwoken/LightGodwokenV1.ts
Changes in the PR:
- Change native asset's info, from 'CKB' to 'pCKB'
- Only changing V1's info
Remaining issues:
- request `wallet_addEthereumChain` won't work for Users who have added godwoken's chain info to their MetaMask, so the changes to native asset info are transparent to them, is there anything we can do?
- On MetaMask, symbols are all `uppercase`, so 'pCKB' on MetaMask is displayed as 'PCKB', does it bother?
=> refactor: rename native asset info

src/components/Withdrawal/WithdrawalItemV1.tsx
There was a bug in the previous commit about estimated time.
Where:
```tsx
{daysLeft && `${daysLeft} day${daysLeft > 1 && "s"}, `}
```
Since `daysLeft` is a Number typed value, and when `daysLeft = 0`, the code above will output "0".
But our expected output is valid time or empty, the output "0" is not what we wanted.
Changing the condition to the following should fix the bug:
```tsx
{daysLeft ? `${daysLeft} day${daysLeft > 1 ? "s" : ""}, ` : ""}
```
=> fix: conditional estimated time

apps/godwoken-bridge/src/components/Withdrawal/RequestWithdrawalV1.tsx, apps/godwoken-bridge/src/utils/inputValidate.ts
The input validate methods didn't considered that pCKB should have 18 decimals when withdrawing.
Fixed the issue by adding the `CKBDecimals` option to the input validate methods, which defaults to `8`.
- #195
=> Fix: ckb validation in withdrawal_v1 route

apps/godwoken-bridge/src/components/Deposit/DepositItem.tsx, apps/godwoken-bridge/src/components/Withdrawal/ListV0.tsx, apps/godwoken-bridge/src/components/Withdrawal/TokenInfoWithAmount.tsx, apps/godwoken-bridge/src/components/Withdrawal/Unlock.tsx, apps/godwoken-bridge/src/components/Withdrawal/WithdrawalItemV0.tsx, apps/godwoken-bridge/src/components/Withdrawal/WithdrawalItemV1.tsx, apps/godwoken-bridge/src/hooks/useL1UnlockHistory.ts, lerna.json, packages/light-godwoken/src/LightGodwokenV0.ts, packages/light-godwoken/src/LightGodwokenV1.ts, packages/light-godwoken/src/__tests__/utils.ts, packages/light-godwoken/src/config/predefined/mainnet.ts, packages/light-godwoken/src/godwokenScanner/requestTypes/withdrawalHistories.ts, packages/light-godwoken/src/lightGodwoken.ts, packages/light-godwoken/src/lightGodwokenProvider.ts, packages/light-godwoken/src/lightGodwokenType.ts, packages/light-godwoken/src/schemas/codecV0.ts, scripts/package.json, scripts/tsconfig.json, scripts/v0/unlock.ts
Some legacy(v0) withdrawal cells are still locked, and the current version of light-godwoken/godwoken-bridge doesn't provide this feature. This PR provides a unlock function in light-godwoken, and a unlock button in `mainnet_v0` of godwoken-bridge.
- Feature: Add method/component to unlock legacy(v0) withdrawal cells
- Feature: Add script to test the unlock feature locally
Please check the following list before merging the PR:
=> Feat: unlock legacy withdrawal cells

apps/godwoken-bridge/src/App.tsx, apps/godwoken-bridge/src/components/Input/CurrencyInputPanel.tsx, apps/godwoken-bridge/src/components/Input/GeneralInputPanel.tsx, apps/godwoken-bridge/src/components/L1Transfer/L1TransferItem.tsx, apps/godwoken-bridge/src/components/L1Transfer/L1TransferList.tsx, apps/godwoken-bridge/src/components/L1Transfer/RequestL1Transfer.tsx, apps/godwoken-bridge/src/components/Layout/PageFooter.tsx, apps/godwoken-bridge/src/components/Layout/PageHeader.tsx, apps/godwoken-bridge/src/hooks/useL1TxHistory.ts, apps/godwoken-bridge/src/index.css, apps/godwoken-bridge/src/style/common.ts, apps/godwoken-bridge/src/utils/inputValidate.ts, apps/godwoken-bridge/src/views/L1Transfer.tsx, packages/light-godwoken/src/__tests__/lightGodwoken.spec.ts, packages/light-godwoken/src/__tests__/lightGodwokenDeposit.spec.ts, packages/light-godwoken/src/constants/error.ts, packages/light-godwoken/src/lightGodwoken.ts, packages/light-godwoken/src/lightGodwokenProvider.ts, packages/light-godwoken/src/lightGodwokenType.ts, packages/light-godwoken/src/utils/async.ts
- Feat: L1 transfer relevant functions in light-godwoken
- Feat: L1 transfer route in godwoken-bridge
- Refactor: refactor Header/Body in godwoken-bridge for better adaptability
- https://github.com/godwokenrises/light-godwoken/issues/189
1. **Different capacity collection strategy**
When depositing, light-godwoken mainly collect capacity from pure CKB cells, and when pure CKB cells are not enough, light-godwoken will then collect capacity from sUDT cells with extra capacity (capacity > 144 CKB).
When l1-transferring, light-godwoken will preferentially collect capacity from sUDT cells with extra capacity (capacity > 144 CKB), and when that is not enough, light-godwoken will then collect capacity from pure CKB cells.
2. **Different exchange strategy**
When depositing, light-godwoken …
=> Feat: l1-transfer

CHANGELOG.md, apps/godwoken-bridge/CHANGELOG.md, apps/godwoken-bridge/package.json, lerna.json, packages/light-godwoken/CHANGELOG.md, packages/light-godwoken/package.json
Publishing light-godwoken v0.3.0 with the latest version of changelog.
=> Chore: bump v0.3.0

apps/godwoken-bridge/src/components/Container/Empty.tsx, apps/godwoken-bridge/src/components/Deposit/List.tsx, apps/godwoken-bridge/src/components/L1Transfer/L1TransferList.tsx, apps/godwoken-bridge/src/components/Layout/PageFooter.tsx, apps/godwoken-bridge/src/components/Layout/PageHeader.tsx, apps/godwoken-bridge/src/components/PopoverMenu/index.tsx, apps/godwoken-bridge/src/components/VersionSelect/index.tsx, apps/godwoken-bridge/src/components/Withdrawal/ListV0.tsx, apps/godwoken-bridge/src/components/Withdrawal/ListV1.tsx, apps/godwoken-bridge/src/index.css, apps/godwoken-bridge/src/views/Deposit.tsx
- Add godwoken-docs's link and light-godwoken's repo link to godwoken-bridge
- Fix some overflow issues in deopsit page, header and footer
- Add Empty component to beautify all empty lists
- #202
- **New added links** 
Added links to [light-godwoken](https://github.com/godwokenrises/light-godwoken) and [godwoken-doc](https://doc.godwoken.io), and beautified the popover list. 
One more fix is originally the popover component won't stick on the screen when we scroll the page, and now it just stick at the page, will not move with the page body when scrolling.
- **Empty lists**
Added a new component `Empty`, now when a list is empty, it displays this component instead.
=> Feat: add project relevant links

packages/light-godwoken/src/tokens/predefined/mainnet.ts, packages/light-godwoken/src/tokens/predefined/testnet.ts
The UANs of `dCKB` (mainnet_v1) are incorrectly defined as: 
- `L1UAN` - YOK.ckb
- `L2UAN` - YOK.gw|gb.ckb
This makes `dCKB` and `YOK` share the same UANs, and can cause serious mistakes in the L1-Transfer page (displaying the wrong balance or choosing the wrong token since L1-Transfer page is using UAN as ID), which should be fixed by this PR. 
- https://github.com/godwokenrises/light-godwoken/issues/223
Thanks to @Dawn-githup for spotting the issue.
=> Fix misplaced uan of `dCKB` and `YOK`

packages/light-godwoken/src/LightGodwokenV0.ts, packages/light-godwoken/src/LightGodwokenV1.ts, packages/light-godwoken/src/godwoken/godwokenV0.ts, packages/light-godwoken/src/godwoken/godwokenV1.ts, packages/light-godwoken/src/godwoken/index.ts, packages/light-godwoken/src/index.ts, packages/light-godwoken/src/lightGodwoken.ts, packages/light-godwoken/src/lightGodwokenType.ts
There's a feature in deposit & withdrawal that if the caller has passed an `EventEmitter` into the deposit/withdraw function, it observes the deposit/withdrawal, which means it will keep requesting the RPC till the deposit/withdrawal has a result (or it will stop after too many cycles).
When I send a deposit/withdraw transaction, I might have to pass an EventEmitter into the function, but I don't always need to observe the result of the action. So I added a `waitForCompletion` option to both deposit and withdraw methods, so if `waitForCompletion !== true`, they just won't observe for the final result anymore.
- Add `waitForCompletion` to deposit/withdraw
- Rename some classes
=> Feat: add `waitForCompletion` to deposit/withdraw

CHANGELOG.md, apps/godwoken-bridge/src/components/Withdrawal/SubmitWithdrawal.tsx, packages/light-godwoken/src/config/predefined/mainnet.ts, packages/light-godwoken/src/config/predefined/testnet.ts
For the latest version of Godwoken V1, the withdrawal finality is relatively stable at:
- `mainnet` - 8.75 days
- `testnet` - 13 mins
So I changed the block produce time in our v1 configs to better match the current status. 
Also I've added a "~" in the withdrawal confirmation dialog, and when submitting, the dialog shows a rounded time.
For instance, on mainnet_v1 it shows `~9 days` instead of `8.75 days`:
```
Estimated time: ~9days
```
- close https://github.com/godwokenrises/light-godwoken/issues/220
Thanks to @alejandroRbit for pointing out the issue
=> Feat: update block produce time on v1 networks

apps/godwoken-bridge/src/components/PopoverMenu/index.tsx
Godwoken Bridge incorrectly shows CKB Faucet link on mainnet.
Adding diplay logic to fix the issue.
=> Fix: ckb faucet should not be displayed on mainnet

CHANGELOG.md, apps/godwoken-bridge/package.json, lerna.json, packages/light-godwoken/package.json
- Publish light-godwoken v0.3.2
- Update [CHANGELOG.md](https://github.com/godwokenrises/light-godwoken/blob/939a890bb386c0ece27126ae0cbf7a1971ccf52d/CHANGELOG.md)
=> Chore: bump v0.3.2

packages/light-godwoken/src/config/predefined/testnet.ts
After updating the RPC URL for Testnet v1, we found an issue in MetaMask that it doesn't like RPC URLs that aren't in the [chainlist](https://github.com/ethereum-lists/chains/blob/fb49612d701926525629ba3f1836d2a58f3475ad/_data/chains/eip155-71401.json) records. The detailed behaviour is that when godwoken-bridge calls the `wallet_addEthereumChain` method, MetaMask warns the user that the new network is not in their record.
After discussion, we decided to remove the `instant-finality-hack` from the RPC URLs in light-godwoken, as this feature is now optional and does not affect operations in light-godwoken. 
Also, we have created a PR to update the info of Godwoken Testnet v1 chain: https://github.com/ethereum-lists/chains/pull/1979.
=> Feat: remove instant-finality-hack from rpc url

apps/godwoken-bridge/src/contexts/LightGodwokenContext.tsx, apps/godwoken-bridge/src/hooks/useL2CKBBalance.ts, apps/godwoken-bridge/src/utils/addNetwork.ts, apps/godwoken-bridge/src/views/GodwokenBridge.tsx
Godwoken Bridge can now detect if the current network has changed.
To be noted, these changes are probably not compatible with the PR #201.
- Add event listener to detect if the current network has changed
- Add check to prevent adding an already existing network
=> Feat: watch network changes

apps/godwoken-bridge/src/components/Withdrawal/ListV1.tsx, apps/godwoken-bridge/src/components/Withdrawal/WithdrawalItemV0.tsx, apps/godwoken-bridge/src/components/Withdrawal/WithdrawalItemV1.tsx, yarn.lock
Previously, pending v1 withdrawals were not properly displayed while waiting to be unlocked.
Now added the logic: when a withdrawal's time is up, it will show a loading indicator instead of "00:00".
Also to improve user experience, I added an interval which reloads the v1 pending withdrawal list every 60 seconds.
Thanks to @Dawn-githup for the suggestion.
- Provides a loading indicator for pending/available withdrawals waiting to be unlocked
- Adds an interval to reload the v1 pending withdrawal list at every 30 seconds
- Update yarn.lock file
=> Feat: improve the display logic of pending withdrawals

apps/godwoken-bridge/craco.config.js, apps/godwoken-bridge/package.json, apps/godwoken-bridge/src/components/ClaimSudt/sudtFaucet.ts, apps/godwoken-bridge/src/components/Deposit/List.tsx, apps/godwoken-bridge/src/components/L1Transfer/RequestL1Transfer.tsx, apps/godwoken-bridge/src/components/Withdrawal/ListV1.tsx, apps/godwoken-bridge/src/components/Withdrawal/Unlock.tsx, apps/godwoken-bridge/src/components/Withdrawal/WithdrawalItemV0.tsx, apps/godwoken-bridge/src/views/Deposit.tsx, packages/light-godwoken/package.json, packages/light-godwoken/src/LightGodwokenV0.ts, packages/light-godwoken/src/LightGodwokenV1.ts, packages/light-godwoken/src/__tests__/clientConfig.ts, packages/light-godwoken/src/__tests__/codec.spec.ts, packages/light-godwoken/src/__tests__/lightGodwoken.spec.ts, packages/light-godwoken/src/__tests__/lightGodwokenDeposit.spec.ts, packages/light-godwoken/src/__tests__/utils.ts, packages/light-godwoken/src/config/predefined/mainnet.ts, packages/light-godwoken/src/config/predefined/testnet.ts, packages/light-godwoken/src/config/types.ts, packages/light-godwoken/src/config/utils.ts, packages/light-godwoken/src/lightGodwoken.ts, packages/light-godwoken/src/lightGodwokenProvider.ts, packages/light-godwoken/src/lightGodwokenType.ts, packages/light-godwoken/src/schemas/codecLayer1.ts, packages/light-godwoken/src/schemas/codecV0.ts, packages/light-godwoken/src/schemas/codecV1.ts, yarn.lock
The version of `ckb-lumos` we depend on is too old, causing some of our features to break. Fixing them by:
- Migrate ckb-lumos to the latest version
- Lock the version of omni_lock in ckb-lumos
- Replace `CkbIndexer.tip()` calls with `CkbRpc.getIndexerTip()`
- resolve #249 
- close #182
- https://lumos-website.vercel.app/migrations/migrate-to-v0.19
- https://lumos-website.vercel.app/migrations/migrate-to-v0.20
=> Ref: migrate ckb-lumos to the latest version

apps/godwoken-bridge/src/contexts/LightGodwokenContext.tsx
A simple UI experience optimization
Display installation reminders in the form of modal windows on browsers without Metamask plug-ins to ensure consistent visual style and avoid repeated reminders
before :
https://user-images.githubusercontent.com/17589354/216362212-18e476aa-f91d-4512-b40a-d6a76f5600f5.mov
after: 
https://user-images.githubusercontent.com/17589354/216362282-4f1a5e5c-6a3f-4c7c-9a76-3de76c4fb80c.mov
=> perf: metamask install tips

apps/godwoken-bridge/src/components/CustomTooltip/index.tsx, apps/godwoken-bridge/src/components/WalletInfo/index.tsx
This pull request fixes the issue
#204
=> fix: QR code tooltip is not gone

apps/godwoken-bridge/src/components/NetworkMismatchModal/index.tsx, apps/godwoken-bridge/src/views/GodwokenBridge.tsx
This pull request optimizes the network switching policy.
When network changes are detected,Not directly switch the network,Instead, the user is notified and asked to switch the network
- fix #254
=> feat: Network switching strategy adjustment

apps/godwoken-bridge/.env.development
Adds a `.env.development`  file to godwoken-bridge, so new developers can run the app without extra help.
And if new developers needs a different env, they can just duplicate the `.env.development` file and name the new file `.env.development.local`, git will not include it.
=> chore: add .env.development

apps/godwoken-bridge/src/components/ClaimSudt/index.tsx
Currently, there is no better solution to avoid `double spend` when constructing transactions, so use the simplest error prompt for processing
- fix #197
=> fix: get TTKN appears duplicated transaction

CHANGELOG.md
Planning to release the `0.4.0` version of light-godwoken tomorrow. This is a version with some breaking changes, and we have new contributors addressing many of our issues, thanks to @GitOfJason @miaosun009. 
Also, while editing the changelog, a question came to my mind: we have so many changes in this version, it would be a little hard to mention contributors for each pull request like before, so should we find a better/simpler way to mention contributions in our changelog?
Here's an example of how we mention a contributor before:
```markdown
- Describe the change (pull/issue number)
> Thanks to @thecontributor for contributing the PR
```
Should we find a simpler way to do it? Like so:
```markdown
- Describe the change (pull/issue number) (@thecontributor)
```
=> chore: bump v0.4.0

apps/godwoken-bridge/src/components/Withdrawal/ListV1.tsx, apps/godwoken-bridge/src/components/Withdrawal/RequestWithdrawalV1.tsx, apps/godwoken-bridge/src/components/Withdrawal/WithdrawalItemV1.tsx, apps/godwoken-bridge/src/views/withdrawal/WithdrawalV1.tsx
1. After successfully initiating a withdrawal, the record will be displayed in the pending list immediately.
2. No longer use the `block_number` of  `withdrawal_histories` to calculate the estimated remaining time
3. This change is only valid for `Godwoken V1`
- fix #171
=> feat: refactor the Withdrawal Pending List

apps/godwoken-bridge/src/components/Withdrawal/ListV1.tsx, apps/godwoken-bridge/src/components/Withdrawal/WithdrawalItemV1.tsx, apps/godwoken-bridge/src/views/withdrawal/WithdrawalV1.tsx
Because the [WithdrawalWithStatus](https://github.com/godwokenrises/godwoken/blob/develop/docs/RPC.md#type-withdrawalwithstatus) from Godwoken RPC only has 2 status: pending | committed, it is not convenient to reveal the status of a failed withdrawal. So, I provide a simple solution:
If a withdrawal stays in l2Pending too long,
then it may have failed for some reason,
such as `over-withdraw`.
Since the data structures of `Pending` and `Completed` withdrawal lists are significantly different, I suggest just putting the failed record stay in the `Pending` list, and removing it after 3 days.
=> Fix the status of a long time l2Pending withdrawal

apps/godwoken-bridge/src/components/Withdrawal/ListV1.tsx
Previously in #300, we wanted to find outdated failed withdrawals in the `localTxHistory` variable and remove them. 
However, in our tests, @Dawn-githup and I discovered that the `failed` status is not updated in the `localTxHistory` variable.
SImply put, here's the `localTxHistory` in withdrawal v1 list:
- When new withdrawals was created, add new item to the `localTxHistory` and save to `localStorage`
- When rendering local pending withdrawals, load `localTxHistory` from `localStorage`
- When a item in `localTxHistory` is completed (comparing with a list from gwscan api), remove it from the `localTxHistory`
You can see there's no status check or update during the variable's lifecycle. Further more, items of the `localTxHistory` in the specific withdrawal v1 list don't have the `status` …
=> Fix: remove outdated failed withdrawals

README.md, apps/godwoken-bridge/package.json
- Remove `yarn install` in Readme file, developers do not need to install packages in `app/godwoken-bridge`
=> Remove `yarn install` in Readme file

apps/godwoken-bridge/src/components/Withdrawal/ListV1.tsx
```javascript
checkL2PendingTimer.current = setInterval(() => {
loadPendingHistory(localTxHistory);
}, 15000);
```
In this problem, the most likely reason is that React's closure behavior is causing the localTxHistory to remain unchanged within the setInterval function. When setInterval is created by useDeepCompareEffect, it saves the value of localTxHistory at that moment, and this value is not updated in subsequent setInterval calls.
One way to solve this problem is to use useRef to maintain a reference to localTxHistory. This way, every time setInterval is executed, we always get the latest value of localTxHistory.
=> fixed multi pending list problem

packages/light-godwoken/src/config/predefined/mainnet.ts
Update the configuration of BLOCK_PRODUCE_TIME of Godwoken mainnet_v1 due to:
- https://github.com/godwokenrises/godwoken/discussions/1087
1. 
2.
=> Update block_interval_seconds of Godwoken mainnet_v1

CHANGELOG.md, apps/godwoken-bridge/package.json, apps/godwoken-bridge/src/components/Withdrawal/ListV1.tsx, packages/light-godwoken/package.json, packages/light-godwoken/src/config/predefined/mainnet.ts, yarn.lock
- https://github.com/godwokenrises/light-godwoken/pull/321
- https://github.com/godwokenrises/light-godwoken/pull/320
=> Sync develop to mainnet 

apps/godwoken-bridge/src/App.tsx, apps/godwoken-bridge/src/components/Layout/PageHeader.tsx, apps/godwoken-bridge/src/components/PhaseOut/PhaseOutCard.tsx, apps/godwoken-bridge/src/components/PhaseOut/ShowOnPhaseOut.tsx, apps/godwoken-bridge/src/components/WalletInfo/index.tsx, apps/godwoken-bridge/src/views/Deposit.tsx, apps/godwoken-bridge/src/views/GodwokenBridge.tsx, apps/godwoken-bridge/src/views/L1Transfer.tsx, apps/godwoken-bridge/src/views/withdrawal/WithdrawalV0.tsx, apps/godwoken-bridge/src/views/withdrawal/WithdrawalV1.tsx
- Add a `PhaseOutCard` alert on all pages that is only visible when `REACT_APP_PHASE_OUT == 'true'`
- Add logic to hide the `Deposit` tab and redirect the app to `/` when `REACT_APP_PHASE_OUT == 'true'`
- Add `hide*` props in `WalletInfo`, and remove address/balance related props, and then display the component in withdraw v0/v1 pages and in l1-transfer page
1. The `REACT_APP_PHASE_OUT` variable is set to `true`  in preview env, and is `false` in production
2. When we need to display the alert in production (testnet/mainnet), we'll have to update its config on Vercel
=> feat: switchable phase-out alert
