godwokenrises/light-godwoken

- src/light-godwoken/constants/index.ts
- src/light-godwoken/lightGodwoken.ts
- src/light-godwoken/lightGodwokenType.ts
- feat: implement deposit interface
- format code
> zhangyouxin

- package.json
- src/light-godwoken/LightGodwokenV0.ts
- src/light-godwoken/godwoken/godwoken.ts
- src/light-godwoken/lightGodwoken.ts
- src/light-godwoken/lightGodwokenType.ts
- src/light-godwoken/schemas/codec.ts
- yarn.lock
> feat: fast withdraw sdk

- package.json
- src/light-godwoken/LightGodwokenV0.ts
- src/light-godwoken/LightGodwokenV1.ts
- src/light-godwoken/debug.ts
- src/light-godwoken/lightGodwoken.ts
- src/light-godwoken/lightGodwokenProvider.ts
- src/light-godwoken/lightGodwokenType.ts
- yarn.lock
feat: sdk support max ckb deposit
> feat: sdk support max ckb deposit

- jest.config.js
- package.json
- src/components/Withdrawal/Unlock.tsx
- src/light-godwoken/LightGodwokenV0.ts
- src/light-godwoken/LightGodwokenV1.ts
- src/light-godwoken/__tests__/lightGodwokenDeposit.spec.ts
- src/light-godwoken/__tests__/lightGodwokenWithdraw.spec.ts
- src/light-godwoken/__tests__/utils.ts
- src/light-godwoken/debug.ts
- src/light-godwoken/godwoken-v1/src/schema_v1/index.ts
- src/light-godwoken/godwoken/godwoken.ts
- src/light-godwoken/lightGodwoken.ts
- src/light-godwoken/lightGodwokenProvider.ts
- src/light-godwoken/lightGodwokenType.ts
- src/light-godwoken/omni-lock/index.ts
- src/light-godwoken/omni-lock/omni.ts
- src/light-godwoken/schemas/index.esm.ts
- tsconfig.json
- yarn.lock
test: add unit test for light godwoken SDK
> test: add unit test for light godwoken SDK

- package.json
- public/index.html
- src/components/Input/CurrencyInputPanel.tsx
- src/components/Input/NumericalInput.tsx
- src/components/Layout/PageFooter.tsx
- src/components/WalletInfo/index.tsx
- src/components/Withdrawal/Unlock.tsx
- src/utils/numberFormat.spec.ts
- src/utils/numberFormat.ts
- src/views/Deposit.tsx
- yarn.lock
* show L1 and L2 address
* fix popover menu close on mobile
* fix copy on metamask Android
* fix unlock modal close
> UI refine 2

- src/utils/formatTokenAmount.ts
> feat: trailing string end zeros

- src/light-godwoken/LightGodwokenV0.ts
- src/light-godwoken/LightGodwokenV1.ts
- src/light-godwoken/lightGodwoken.ts
- src/light-godwoken/lightGodwokenProvider.ts
- src/light-godwoken/lightGodwokenType.ts
- feat: add deposit with event emitter
- feat: add subscribable withdrawal
- feat: check deposit cell unlocker
> tx history sdk

- src/components/Deposit/DepositItem.tsx
- src/components/Withdrawal/WithdrawalItemV0.tsx
- src/components/Withdrawal/WithdrawalItemV1.tsx
Make it easier for user to check transaction details and do not need to refresh the current operation page.
> feat: open transaction link in new tab for convenience

- package.json
- yarn.lock
https://stackoverflow.com/questions/70368760/react-uncaught-referenceerror-process-is-not-defined
> fix: undefined process.env

- src/components/ClaimSudt/index.tsx
- src/components/Deposit/DepositItem.tsx
- src/components/Withdrawal/WithdrawalItemV1.tsx
This PR for: 
- the pending is unnecessary in a pending list
- some typo
- ensure the uncaught error will be sent to sentry
> chore: remove unnecessary pending

- src/components/Withdrawal/RequestWithdrawalV0.tsx
- src/components/Withdrawal/RequestWithdrawalV1.tsx
- src/light-godwoken/LightGodwokenV0.ts
- src/light-godwoken/LightGodwokenV1.ts
- src/light-godwoken/__tests__/lightGodwokenConfig.ts
- src/light-godwoken/constants/configTypes.ts
- src/light-godwoken/constants/lightGodwokenConfig.ts
- src/light-godwoken/lightGodwoken.ts
- src/utils/__tests__/dateUtils.spec.ts
- src/utils/dateUtils.ts
fix: correct withdrawal prompt wait time
> fix: correct withdrawal prompt wait time

- src/components/Input/CurrencyInputPanel.tsx
This pr enhances:
- display user token list in a proper order that tokens which user don't have will move down
> feat: sort token list by user balance

- scripts/README.md
- scripts/context.ts
- src/light-godwoken/constants/lightGodwokenConfig.ts
supported `multicall` to avoid https://github.com/nervosnetwork/light-godwoken/issues/136 ,this `multicall` contract may replace with https://github.com/mds1/multicall/issues/33 in the future
> feat: supported multicall on v1 mainnet

- src/components/Input/CurrencyInputPanel.tsx
This pr fixes bug reported in https://github.com/nervosnetwork/light-godwoken/issues/156
> fix: fix selected ERC20 balance errror on withdrawal page

- README.md
- docs/introduction.md
mainnet.bridge.godwoken.io -> bridge.godwoken.io
> docs: update mainnet bridge url

- src/components/Input/CurrencyInputPanel.tsx
motivation: the token list seems chaotic.
This pr has sorted the token list in dictionary order.
> feat: sort token by dict order

- src/components/Withdrawal/WithdrawalItemV1.tsx
Related issue:
- https://github.com/nervosnetwork/light-godwoken/issues/168
Changes in the PR:
- Fix estimated time in withdrawal history V1
- Fix vertical align of WithdrawalItemvV1
> fix: estimated time in withdrawal history V1

- .gitignore
- src/components/Withdrawal/WithdrawalItemV1.tsx
- src/light-godwoken/LightGodwokenV1.ts
> chore: sync with develop

- apps/godwoken-bridge/src/components/Withdrawal/Unlock.tsx
Error handling logic in unlock page is incomplete, filling it up.
> Fix error handling in unlock

- apps/godwoken-bridge/craco.config.js
Sentry is no longer used in the project, disabling it.
> chore: disable sentry

- apps/godwoken-bridge/src/components/Withdrawal/WithdrawalItemV0.tsx
- apps/godwoken-bridge/src/components/Withdrawal/WithdrawalTarget.tsx
- Fix withdrawal time left for fast withdrawals, now for fast withdrawals we hide the estimated time
- Fix typo in withdrawal v0 panel
> Fix: fast withdrawal left time

- CHANGELOG.md
- apps/godwoken-bridge/package.json
- lerna.json
- packages/light-godwoken/package.json
- Publish light-godwoken v0.3.3
- Update [CHANGELOG.md](https://github.com/godwokenrises/light-godwoken/blob/af93bccdbb3946c3acd93c2874523d2a74730807/CHANGELOG.md)
> Chore: bump v0.3.3

- apps/godwoken-bridge/craco.config.js
- apps/godwoken-bridge/package.json
- apps/godwoken-bridge/public/index.html
- apps/godwoken-bridge/src/components/PopoverMenu/index.tsx
- apps/godwoken-bridge/src/components/QrCodeModal/index.tsx
- apps/godwoken-bridge/src/components/WalletInfo/index.tsx
- Added an "About (#commit-hash)" button to the menu's popover
- Added an "Open in explorer" link button in Address Details modal
- Beautified the style of noscript page
1. The "About" link button
2. The "Open in explorer" button
3. The beautified noscript page
- resolves https://github.com/godwokenrises/light-godwoken/issues/250
- resolves https://github.com/godwokenrises/light-godwoken/issues/252
> Feat: friendly ux changes

- apps/godwoken-bridge/src/components/Withdrawal/RequestWithdrawalV0.tsx
- apps/godwoken-bridge/src/components/Withdrawal/RequestWithdrawalV1.tsx
- apps/godwoken-bridge/src/components/Withdrawal/SubmitWithdrawal.tsx
This pull request fixes the issue
#207
> fix: Withdrawal Confirmation page can't be closed

- apps/godwoken-bridge/src/views/GodwokenBridge.tsx
Repair the network name displayed when prompted to switch network
- fix https://github.com/godwokenrises/light-godwoken/pull/260#issuecomment-1423857524
> fix: network display name

- apps/godwoken-bridge/src/components/Layout/PageHeader.tsx
- apps/godwoken-bridge/src/index.css
Our Godwoken NFT Bridge demo has been released for a few days. Although the demo is still under development, the main features are provided and we do need more public advices/suggestions. So I think this would be a good time to share it with users who would felt interested to try it out.
- Disable the custom style of scrollbar
- Refactor the header component, make it more appropriate
- Add [the link of NFT Bridge (beta)](https://testnet.nft-bridge.godwoken.io) to the header component
> feat: NFT Bridge link in PageHeader

- apps/godwoken-bridge/package.json
- apps/godwoken-bridge/src/components/ClaimSudt/sudtFaucet.ts
- packages/light-godwoken/package.json
- packages/light-godwoken/src/__tests__/lightGodwoken.spec.ts
- packages/light-godwoken/src/__tests__/lightGodwokenDeposit.spec.ts
- packages/light-godwoken/src/lightGodwoken.ts
- packages/light-godwoken/src/lightGodwokenProvider.ts
- scripts/v0/unlock.ts
- yarn.lock
Related:
- https://github.com/nervosnetwork/ckb-indexer/pull/64
- https://github.com/ckb-js/lumos/pull/491
> refactor: Bump lumos version and use exact search mode

- CHANGELOG.md
- apps/godwoken-bridge/package.json
- apps/godwoken-bridge/src/components/ClaimSudt/sudtFaucet.ts
- apps/godwoken-bridge/src/components/Withdrawal/ListV1.tsx
- apps/godwoken-bridge/src/components/Withdrawal/WithdrawalItemV1.tsx
- apps/godwoken-bridge/vite.config.ts
- packages/light-godwoken/package.json
- packages/light-godwoken/src/__tests__/lightGodwoken.spec.ts
- packages/light-godwoken/src/__tests__/lightGodwokenDeposit.spec.ts
- packages/light-godwoken/src/lightGodwoken.ts
- packages/light-godwoken/src/lightGodwokenProvider.ts
- scripts/v0/unlock.ts
- yarn.lock
Tag `0.4.3` is released:
https://github.com/godwokenrises/light-godwoken/releases/tag/0.4.3
Now synchronizing `develop@0.4.3` to `main`.
> Sync `develop@0.4.3` to main

- README.md
- apps/godwoken-bridge/package.json
- add how to run development script in readme file
- add open browser directly in developmen env
> update readme file and godwoken bridge script for development

- CHANGELOG.md
- README.md
- apps/godwoken-bridge/package.json
- apps/godwoken-bridge/src/components/Withdrawal/ListV1.tsx
- yarn.lock
- update script and fixed multi pending list problem [#311](https://github.com/godwokenrises/light-godwoken/pull/311)
> Sync develop@0.4.4 to mainnet

- CHANGELOG.md
- apps/godwoken-bridge/package.json
- apps/godwoken-bridge/src/components/Withdrawal/ListV1.tsx
- packages/light-godwoken/package.json
Prepare to sync develop branch to mainnet branch next week.
- https://github.com/godwokenrises/light-godwoken/pull/317
- https://github.com/godwokenrises/godwoken/discussions/1087
> Bump Godwoken Bridge to 0.4.5
